import type {Metadata} from 'next';
const copy={
  about:{ro:['Despre Volmer | Soluții pentru auz în Chișinău','Află cum oferă Volmer explicații clare, soluții auditive Unitron și suport individual în Chișinău.'],ru:['О Volmer | Решения для слуха в Кишинёве','Узнайте о подходе Volmer, решениях Unitron и индивидуальной поддержке в Кишинёве.']},
  faq:{ro:['Întrebări frecvente despre auz și aparate | Volmer','Răspunsuri clare despre evaluarea auzului, aparate auditive, reglare și programări la Volmer.'],ru:['Вопросы о слухе и слуховых аппаратах | Volmer','Понятные ответы об оценке слуха, аппаратах, настройке и записи в Volmer.']},
  programare:{ro:['Programare telefonică pentru evaluarea auzului | Volmer','Sună Volmer pentru a programa evaluarea auzului sau o consultație despre aparate auditive în Chișinău.'],ru:['Запись на оценку слуха по телефону | Volmer','Позвоните в Volmer, чтобы записаться на оценку слуха или консультацию в Кишинёве.']},
  contact:{ro:['Volmer Chișinău | Aparate auditive și test auditiv','Contactează Volmer în Chișinău pentru aparate auditive Unitron, evaluarea auzului și programări telefonice.'],ru:['Volmer Кишинёв | Слуховые аппараты и проверка слуха','Контакты Volmer в Кишинёве: аппараты Unitron, оценка слуха и запись по телефону.']},
  'test-auditiv':{ro:['Test auditiv și evaluarea auzului în Chișinău | Volmer','Evaluarea auzului în Chișinău, explicații clare și programare telefonică la Volmer.'],ru:['Проверка и оценка слуха в Кишинёве | Volmer','Оценка слуха в Кишинёве, понятные объяснения и запись по телефону в Volmer.']},
  servicii:{ro:['Reglare și service aparate auditive în Chișinău | Volmer','Reglare, întreținere și service pentru aparate auditive în Chișinău, cu suport Volmer.'],ru:['Настройка и сервис слуховых аппаратов в Кишинёве | Volmer','Настройка, уход и сервис слуховых аппаратов в Кишинёве с поддержкой Volmer.']}
} as const;
export function pageMetadata(locale:string,page:keyof typeof copy):Metadata{const lang=locale==='ru'?'ru':'ro';const [title,description]=copy[page][lang];const slug=page==='about'?'despre-noi':page==='faq'?'intrebari-frecvente':page;const path=`/${lang}/${slug}/`;return {title,description,alternates:{canonical:path,languages:{'ro-MD':`/ro/${slug}/`,'ru-MD':`/ru/${slug}/`,'x-default':`/ro/${slug}/`}},openGraph:{title,description,url:path,type:'website'},twitter:{card:'summary',title,description}};}
