import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {setRequestLocale} from 'next-intl/server';
import {blogPosts,type Locale} from '@/content/seo';
import {siteConfig} from '@/config/site';

export function generateStaticParams(){return (['ro','ru'] as Locale[]).flatMap(locale=>blogPosts[locale].map(post=>({locale,slug:post.slug})));}
function findPost(locale:Locale,slug:string){return blogPosts[locale].find(post=>post.slug===slug);}
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}):Promise<Metadata>{const p=await params;const locale=p.locale as Locale;const post=findPost(locale,p.slug);if(!post)return {};const path=`/${locale}/blog/${p.slug}/`;return {title:`${post.title} | Volmer`,description:post.description,keywords:post.keywords,alternates:{canonical:path,languages:{[locale==='ro'?'ro-MD':'ru-MD']:path,'x-default':path}},openGraph:{title:post.title,description:post.description,type:'article',url:path,publishedTime:post.publishedAt,modifiedTime:post.updatedAt},twitter:{card:'summary',title:post.title,description:post.description}};}
export default async function Article({params}:{params:Promise<{locale:string;slug:string}>}){const p=await params;const locale=(p.locale==='ru'?'ru':'ro') as Locale;setRequestLocale(locale);const post=findPost(locale,p.slug);if(!post)notFound();const related=post.relatedArticles.map(slug=>findPost(locale,slug)).filter(Boolean);const url=`${siteConfig.siteUrl}/${locale}/blog/${post.slug}/`;const jsonLd=[{'@context':'https://schema.org','@type':'BlogPosting',headline:post.title,description:post.description,datePublished:post.publishedAt,dateModified:post.updatedAt,author:{'@type':'Organization',name:post.author},publisher:{'@type':'Organization',name:'Volmer'},mainEntityOfPage:url},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:locale==='ro'?'Acasă':'Главная',item:`${siteConfig.siteUrl}/${locale}/`},{'@type':'ListItem',position:2,name:'Blog',item:`${siteConfig.siteUrl}/${locale}/blog/`},{'@type':'ListItem',position:3,name:post.title,item:url}]}];return <article className="container page blog-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><nav className="breadcrumb" aria-label="Breadcrumb"><a href={`/${locale}/`}>{locale==='ro'?'Acasă':'Главная'}</a> / <a href={`/${locale}/blog/`}>Blog</a> / {post.title}</nav><p className="blog-meta">{post.category} · {post.readingTime} · <time dateTime={post.publishedAt}>{post.publishedAt}</time></p><h1>{post.title}</h1><p className="lead">{post.description}</p>{post.sections.map(section=><section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}<p className="article-disclaimer">{locale==='ro'?'Informațiile sunt generale și nu înlocuiesc o evaluare individuală a auzului.':'Информация носит общий характер и не заменяет индивидуальную оценку слуха.'}</p><div className="actions"><a className="button stone" href={`tel:${siteConfig.phoneInternational}`}>{locale==='ro'?'Sună pentru programare':'Позвонить для записи'}</a><a className="button ghost" href={`/${locale}/aparate-auditive/`}>{locale==='ro'?'Aparate auditive':'Слуховые аппараты'}</a></div><section className="related"><h2>{locale==='ro'?'Articole recomandate':'Рекомендуемые статьи'}</h2>{related.map(item=><p key={item!.slug}><a href={`/${locale}/blog/${item!.slug}/`}>{item!.title}</a></p>)}</section></article>}
